default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: ethio_www_development

test:
  <<: *default
  database: ethio_www_test

production:
  <<: *default
  database: ethio_www_production
  username: ethio_www
  password: <%= ENV['ETHIO_WWW_DATABASE_PASSWORD'] %>
