default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: eefio_www_development

test:
  <<: *default
  database: eefio_www_test

production:
  <<: *default
  database: eefio_www_production
  username: eefio_www
  password: <%= ENV['ETHIO_WWW_DATABASE_PASSWORD'] %>
